version: "3.7"
 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sprite-generator
    volumes:
      - ./tmp:/app/tmp
      - ./assets:/app/assets
      - ./src:/app/src