version: "3.7"
 
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sprite-generator
    volumes:
      - ./tmp:/app/tmp
      - ./assets:/app/assets
      - ./src:/app/src
    command: npm run dev